### ISSUE TITLE
Broken frontend after using repeater

### ISSUE THREAD

**Issue by Olekrut** [maxi-blocks/maxi-blocks#5353]
### Description

Not sure, but guess, everything gets brake after using repeater, but only for this code, cant reproduce it in another way

### Step-by-step reproduction instructions

1) use code
2) check frontend

### Screenshots, screen recording, code snippet

https://jam.dev/c/cd695d21-919e-4f21-a5a1-45e9cee6f60c

### URL and/or Code editor

[bug.txt](https://github.com/maxi-blocks/maxi-blocks/files/13726962/bug.txt)

**Comment by elzadj** [comment]
Can't add it to backend, the code doesn't work, could you please link to the page on 3devdemo @Olekrut ?

**Comment by elzadj** [comment]
![screenshot-wordpress local-2023 12 21-16_37_43](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/9c2ed675-41ee-4ee1-ba76-43f299239188)

that's weird, figuring it out

**Comment by elzadj** [comment]
Ok, it was broken because of a manually added css.

But it looks like repeater fails to add the id for IB in the 3rd column (2nd one is fine):

![screenshot-wordpress local-2023 12 22-17_58_49](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/e2573c6f-ce07-4dab-add5-7a6e2b4f7006)

![screenshot-wordpress local-2023 12 22-18_04_26](https://github.com/maxi-blocks/maxi-blocks/assets/2401618/d4de75d7-489a-4929-85e0-9905d5ae5264)
